export const TOGGLE_SEEN_STATUS = "TOGGLE_SEEN_STATUS";
export const REMOVE_SEEN_STATUS = "REMOVE_SEEN_STATUS";
export const SEARCH_TITLE = "SEARCH_TITLE";
export const CHANGE_SHOW_SET = "CHANGE_SHOW_SET";
export const UPDATE_STATUS_COUNT = "UPDATE_STATUS_COUNT";

export const CHANGE_FILM_SET = "CHANGE_FILM_SET";
export const CHANGE_EMAIL = "CHANGE_EMAIL";
export const CHANGE_NAME = "CHANGE_NAME";

export const GET_FILMS_SUCCESS = "GET_FILMS_SUCCESS";
export const GET_FILMS_FAIL = "GET_FILMS_FAIL"

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const LOGOUT_ALL = "LOGOUT_ALL";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";