export const TOGGLE_SEEN_STATUS = "TOGGLE_SEEN_STATUS";
export const REMOVE_SEEN_STATUS = "REMOVE_SEEN_STATUS";
export const SEARCH_TITLE = "SEARCH_TITLE";
export const CHANGE_SHOW_SET = "CHANGE_SHOW_SET";
