export const TOGGLE_SEEN_STATUS = 'TOGGLE_SEEN_STATUS';
export const TOGGLE_SEEN_STATUS_SUCCESS = 'TOGGLE_SEEN_STATUS_SUCCESS';
export const TOGGLE_SEEN_STATUS_FAIL = 'TOGGLE_SEEN_STATUS_FAIL';

export const DELETE_SEEN_STATUS = 'DELETE_SEEN_STATUS';
export const DELETE_SEEN_STATUS_SUCCESS = 'DELETE_SEEN_STATUS_SUCCESS';
export const DELETE_SEEN_STATUS_FAIL = 'DELETE_SEEN_STATUS_FAIL';

export const SEARCH_TITLE = 'SEARCH_TITLE';
export const CHANGE_SHOW_SET = 'CHANGE_SHOW_SET';
export const UPDATE_STATUS_COUNT = 'UPDATE_STATUS_COUNT';

export const CHANGE_FILM_SET = 'CHANGE_FILM_SET';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';

export const GET_SEEN_STATUS_SUCCESS = 'GET_SEEN_STATUS_SUCCESS';
export const GET_SEEN_STATUS_FAIL = 'GET_SEEN_STATUS_FAIL';

export const GET_FILMS_SUCCESS = 'GET_FILMS_SUCCESS';
export const GET_FILMS_FAIL = 'GET_FILMS_FAIL';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_ALL = 'LOGOUT_ALL';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
